-- H2 용 (애플리케이션 시작 시 자동 실행). Oracle 은 docs/oracle-ddl.sql 을 직접 실행하세요.
-- 문서 JSON 본문과 갱신 시각을 저장합니다.
CREATE TABLE IF NOT EXISTS HERO_DOC (
  COL_NAME VARCHAR(30)  NOT NULL,
  DOC_ID   VARCHAR(60)  NOT NULL,
  BODY     TEXT         NOT NULL,
  UPD_DT   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (COL_NAME, DOC_ID)
);

-- 로그인 계정과 BCrypt 비밀번호 해시 및 역할을 저장합니다.
CREATE TABLE IF NOT EXISTS HERO_ACCOUNT (
  USERNAME     VARCHAR(30)  NOT NULL PRIMARY KEY,
  PASSWORD_HASH VARCHAR(100) NOT NULL,
  ROLE_NAME    VARCHAR(20)  NOT NULL DEFAULT 'USER',
  CREATED_AT   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- 가입 승인 상태(PENDING/APPROVED). 기존 계정은 승인된 것으로 간주합니다.
ALTER TABLE HERO_ACCOUNT ADD COLUMN IF NOT EXISTS STATUS VARCHAR(10) DEFAULT 'APPROVED' NOT NULL;

-- 계정별 캐릭터 정보를 저장하며 계정당 하나만 허용합니다.
CREATE TABLE IF NOT EXISTS HERO_CHARACTER (
  CHARACTER_ID VARCHAR(60)  NOT NULL PRIMARY KEY,
  OWNER_ID     VARCHAR(30)  NOT NULL,
  NICKNAME     VARCHAR(30)  NOT NULL,
  GENDER       VARCHAR(1)   NOT NULL,
  TITLE        VARCHAR(8),
  JOB          VARCHAR(16),
  UNIVERSE     VARCHAR(30),
  CREATED_AT   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_HERO_CHARACTER_ACCOUNT FOREIGN KEY (OWNER_ID) REFERENCES HERO_ACCOUNT (USERNAME)
);
